# Generated by Django 5.2.4 on 2025-07-08 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0002_initial"),
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingslog",
            name="mailings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalogs",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
