# Generated by Django 5.2.4 on 2025-07-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "messages_subject",
                    models.CharField(max_length=100, verbose_name="Тема письма"),
                ),
                ("messages_body", models.TextField(verbose_name="Текст письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["messages_subject"],
                "permissions": [("can_view_message", "Can view message")],
            },
        ),
    ]
